import type { Capability } from '../../contracts/src/index.js';
import { Schema as S } from './schema.js';
export class Creator2SkeletonMixCapabilities {
  list(): Capability[] {
    const spine: Capability[] = ['inspect', 'update'].map(action => ({ id: `runtime.spine.mix.${action}`, title: `Creator 2 Spine 动画混合：${action}`, description: '查询或配置动画对过渡秒数；update 必须携带查询得到的 duration/defaultDuration/overrideDuration 作为 expected，duration=null 移除显式覆盖并恢复默认继承。仅影响之后新建的实时动画轨道。', module: 'F20', context: 'runtime', effect: action === 'inspect' ? 'read' : 'runtime',
      inputSchema: S.object({ componentId: S.string(), from: S.string(), to: S.string(), ...(action === 'update' ? { duration: { anyOf: [{ type: 'number', minimum: 0, maximum: 30 }, { type: 'null' }] }, expected: S.record() } : {}) }, ['componentId', 'from', 'to', ...(action === 'update' ? ['duration', 'expected'] : [])]), outputSchema: {}, versions: [2], supportedMajors: [2], implementation: 'implemented', verification: 'unverified', prerequisites: ['Creator 2.4.15；Spine realtime mode'], rollback: '使用本次 after 作 expected，before.overrideDuration 作 duration 显式恢复；不改已播放轨道或项目资源' }));
    return [...spine, { id: 'runtime.dragonbones.fade', title: 'Creator 2 DragonBones 分层混合播放', description: '按原生图层和分组淡入动画，显式选择淡出规则；single 可能复用现有状态。仅实时模式，返回调用前后状态。', module: 'F20', context: 'runtime', effect: 'runtime', inputSchema: S.object({ componentId: S.string(), name: S.string(), duration: { type: 'number', minimum: 0, maximum: 30 }, layer: { type: 'integer', minimum: 0, maximum: 31 }, group: { type: 'string', maxLength: 64 }, playTimes: { type: 'integer', minimum: 0, maximum: 100 }, fadeOutMode: { type: 'string', enum: ['none', 'sameLayer', 'sameGroup', 'sameLayerAndGroup', 'all', 'single'] } }, ['componentId', 'name', 'duration']), outputSchema: {}, versions: [2], supportedMajors: [2], implementation: 'implemented', verification: 'unverified', prerequisites: ['Creator 2.4.15；DragonBones realtime mode'], rollback: '不能恢复已推进的业务动画时间线；根据原生状态显式重新播放' }];
  }
}
