import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { CocosApplication, ProjectRegistry } from '../packages/application/src/index.js';
import { RuntimeGateway } from '../packages/application/src/runtime-gateway.js';
import { CocosError, Json, type JsonObject } from '../packages/contracts/src/index.js';
const project = resolve('.codex-work/build/creator2-test-project'), registry = new ProjectRegistry(), { projectId } = await registry.add(project);
const gateway = new RuntimeGateway(registry), gatewayPort = await gateway.start(), app = new CocosApplication(registry, undefined, undefined, true, gateway);
const rows: JsonObject[] = []; let preview = false;
const call = async (id: string, params: JsonObject = {}): Promise<JsonObject> => { const result = Json.object((await app.execute({ projectId, capabilityId: id, params })).result); rows.push({ id, result }); console.log(`PASS ${id}`); return result; };
try {
  const data = await call('asset.resolve', { reference: 'db://assets/Textures/Creator2SkeletonFixtures/Spine/raptor.json' });
  const scene = Json.object((await call('scene.query')).scene).sceneId!;
  const nodeId = (await call('node.create', { parentId: scene, name: `SpineMix-${Date.now()}` })).nodeId!;
  const editorComponent = (await call('component.add', { nodeId, type: 'sp.Skeleton' })).componentId!;
  await call('component.set', { componentId: editorComponent, properties: { skeletonData: { uuid: data.uuid! }, timeScale: 1 } });
  await call('scene.save'); await call('preview.start', { width: 800, height: 600, visible: true }); preview = true;
  await call('shader.preview.connect', { gatewayPort });
  const hierarchy = (await call('runtime.hierarchy', { limit: 2000 })).rows as JsonObject[];
  const componentId = ((hierarchy.find(row => row.nodeId === nodeId)!.components as JsonObject[]).find(row => row.type === 'sp.Skeleton'))!.componentId!;
  const names = (await call('runtime.spine.inspect', { componentId })).animations as string[];
  assert.ok(names.includes('walk') && names.includes('Jump'));
  const pair = { componentId, from: 'walk', to: 'Jump' };
  const before = await call('runtime.spine.mix.inspect', pair);
  const expected = (value: JsonObject): JsonObject => ({ duration: value.duration!, defaultDuration: value.defaultDuration!, overrideDuration: value.overrideDuration! });
  const reverse = await call('runtime.spine.mix.inspect', { componentId, from: 'Jump', to: 'walk' });
  const change = await call('runtime.spine.mix.update', { ...pair, duration: 1.2, expected: expected(before) });
  assert.equal(Json.object(change.after).overrideDuration, 1.2);
  await assert.rejects(() => call('runtime.spine.mix.update', { ...pair, duration: 0.2, expected: expected(before) }), error => CocosError.from(error).code === 'OPERATION_CONFLICT');
  assert.equal((await call('runtime.spine.mix.inspect', pair)).duration, 1.2);
  assert.deepEqual(await call('runtime.spine.mix.inspect', { componentId, from: 'Jump', to: 'walk' }), reverse);
  await call('runtime.spine.play', { componentId, name: 'walk', loop: true });
  await call('runtime.shader.profile', { frames: 3, warmupFrames: 1 });
  await call('runtime.spine.play', { componentId, name: 'Jump', loop: true });
  await call('runtime.shader.profile', { frames: 3, warmupFrames: 1 });
  const transitioning = (await call('runtime.spine.details', { componentId })).tracks as JsonObject[];
  assert.equal(transitioning[0]!.mixDuration, 1.2); assert.equal(transitioning[0]!.mixingFrom, 'walk');
  assert.ok(Number(transitioning[0]!.mixTime) > 0 && Number(transitioning[0]!.mixTime) < 1.2);
  await call('runtime.shader.profile', { frames: 200, warmupFrames: 1 });
  const completed = (await call('runtime.spine.details', { componentId })).tracks as JsonObject[];
  assert.equal(completed[0]!.animation, 'Jump'); assert.equal(completed[0]!.mixingFrom, null);
  const restored = await call('runtime.spine.mix.update', { ...pair, duration: before.overrideDuration!, expected: Json.object(change.after) });
  assert.deepEqual(restored.after, expected(before));
  await call('runtime.invoke', { target: 'component:' + componentId, method: 'setAnimationCacheMode', args: [1] });
  await assert.rejects(() => call('runtime.spine.mix.inspect', pair), error => CocosError.from(error).code === 'UNSUPPORTED_CAPABILITY');
  await call('runtime.set', { target: `node:${nodeId}`, path: 'active', value: false });
  rows.push({ passed: true, nativeMixTransitionVerified: true, staleWriteRejected: true, unrelatedPairPreserved: true, originalOverrideRestored: true, cachedModeRejected: true });
} catch (error) { rows.push({ passed: false, error: CocosError.from(error).toJSON() as unknown as JsonObject }); process.exitCode = 1; console.error(error); }
finally { try { if (preview) await call('preview.stop'); } finally { await gateway.close(); await mkdir(resolve('.codex-work/logs/creator2-expansion'), { recursive: true }); await writeFile(resolve('.codex-work/logs/creator2-expansion/spine-mix.json'), JSON.stringify({ project, rows }, null, 2)); } }
