import { VerificationBuild } from './verification.mjs';
import { build } from 'esbuild';
import { readdir, mkdir } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { join } from 'node:path';

const verification = new VerificationBuild();
await verification.clear();
const sourceFingerprint = await verification.fingerprint();
const sources = (await readdir('tests')).filter(path => path.endsWith('.test.ts')).map(path => join('tests', path));
if (!sources.length) throw new Error('No tests found');
const output = '.codex-work/build/tests';
await mkdir(output, { recursive: true });
await build({ entryPoints: sources, outdir: output, outExtension: { '.js': '.mjs' }, bundle: true, packages: 'external', platform: 'node', target: 'node24', format: 'esm', sourcemap: true });
const paths = sources.map(path => join(output, path.split('/').pop().replace(/\.ts$/, '.mjs')));
await mkdir('.codex-work/logs', { recursive: true });
const evidencePath = '.codex-work/logs/verification-tests.jsonl';
const processTest = spawn(process.execPath, ['--test', '--test-concurrency=1', '--test-reporter=spec', '--test-reporter-destination=stdout', '--test-reporter=./scripts/test-evidence-reporter.mjs', `--test-reporter-destination=${evidencePath}`, ...paths], { stdio: 'inherit', env: process.env });
processTest.on('error', error => { console.error(error); process.exitCode = 1; });
const code = await new Promise((resolve, reject) => { processTest.once('error', reject); processTest.once('close', resolve); });
process.exitCode = code ?? 1;
if (code === 0) await verification.record(sourceFingerprint, sources, evidencePath);
