/** 面板能力说明；能力 ID 与协议中的原始目录保持稳定。 */
export const capabilityEnglish: Record<string, string> = {
  'editor.status': 'Read editor instance, version and scene status',
  'scene.query': 'Read current scene information and dirty state',
  'scene.snapshot': 'Serialize a replayable snapshot of the current scene',
  'scene.diff': 'Compare the current scene with a baseline snapshot',
  'scene.hierarchy': 'Read scene hierarchy with pagination',
  'scene.open': 'Open a scene; reject switching with unsaved changes',
  'scene.save': 'Save the current scene and check its dirty state',
  'scene.save_copy': 'Save a new scene asset while preserving the current scene and dirty state',
  'scene.create': 'Create an empty scene through the editor',
  'scene.close': 'Close a saved scene',
  'scene.undo': 'Undo the last edit', 'scene.redo': 'Redo the last edit',
  'node.query': 'Read node and component properties',
  'node.find': 'Find all nodes matching a name or scene path',
  'node.create': 'Create a node and return its actual information',
  'node.delete': 'Delete a node', 'node.duplicate': 'Duplicate a node',
  'node.reparent': 'Change the parent, optionally preserving world transforms',
  'node.set': 'Edit node properties and verify by reading back', 'node.reset': 'Reset node transforms',
  'component.types': 'List all registered project components',
  'component.add': 'Add a built-in or project script component',
  'component.query': 'Read property descriptors for a component instance',
  'component.delete': 'Delete a component by instance ID',
  'component.set': 'Edit component properties and references, then verify',
  'component.reset': 'Reset a component instance',
  'component.invoke': 'Invoke a component method; project scripts may have arbitrary side effects',
  'asset.query': 'Query assets by type and path', 'asset.info': 'Read asset information',
  'asset.meta': 'Read import settings', 'asset.dependencies': 'Query direct asset dependencies',
  'asset.users': 'Query asset references',
  'asset.location': 'Plan a resource path by reusing an existing type folder; does not write assets',
  'asset.organize.plan': 'Preview asset organization; root only by default, skipping path-sensitive assets. Review string-based loading paths.',
  'asset.organize.apply': 'Apply a reviewed plan with matching scope and planHash; move via AssetDB, verify UUIDs and return rollback paths',
  'asset.create': 'Create a text asset through AssetDB', 'asset.save': 'Save a text asset through AssetDB',
  'asset.import': 'Import a file within the project', 'asset.copy': 'Copy an asset and its metadata',
  'asset.move': 'Move an asset while preserving its UUID', 'asset.delete': 'Delete an asset',
  'asset.refresh': 'Refresh an asset and wait for import', 'asset.reimport': 'Reimport an asset',
  'asset.set_meta': 'Merge import settings and reimport', 'asset.resolve': 'Convert between asset URL, UUID and file path',
  'prefab.instantiate': 'Instantiate a prefab in the scene', 'prefab.create': 'Save a node as a prefab asset',
  'prefab.apply': 'Apply instance changes to the prefab asset', 'prefab.revert': 'Revert prefab instance changes',
  'prefab.unlink': 'Unlink a prefab instance',
  'view.query': 'Read scene view, gizmo and grid state', 'view.set': 'Change scene view, gizmo and grid settings',
  'view.focus': 'Focus a node', 'selection.query': 'Read editor selection', 'selection.set': 'Set editor selection',
  'project.settings.get': 'Read project settings without global user credentials', 'project.settings.set': 'Edit project settings',
  'editor.messages': 'List editor messages discovered in this version',
  'editor.message': 'Invoke a discovered editor message; internal APIs require an exact version match',
  'scene.script': 'Call a scene script method of an installed extension',
  'preview.start': 'Start preview; Creator 3.8.8 uses a dedicated MCP window and requires a saved scene',
  'preview.resize': 'Resize MCP preview and capture a rendered frame; layout correctness needs review',
  'preview.input': 'Send click or wheel input to the MCP preview and capture a frame; focuses the window, business results need verification',
  'preview.stop': 'Stop project preview',
  'preview.logs': 'Query session preview errors and network failures with pagination and capture-gap reporting',
  'preview.status': 'Read MCP preview window status and recent rendering diagnostics',
  'preview.capture': 'Capture a rendered preview frame without requiring a runtime gateway',
  'logs.query': 'Query bridge events by level and page; use console.query for Creator console logs',
  'console.query': 'Read Creator console errors and stacks, filtered by level, process, keyword and cursor',
  'ui.diff': 'Compare existing UI properties while preserving UUIDs; report structural changes separately',
  'ui.apply': 'Update UI properties in place using planHash; preserve conflicts without deleting and rebuilding',
  'ui.plan': 'Plan declarative UI, checking version, references and name conflicts; return planHash',
  'ui.build': 'Build the planned UI tree and return UUID mappings; compensate partial failures locally',
  'ui.inspect_layout': 'Read actual UI corners and world bounds; detect zero size and parent overflow',
  'ui.validate_interaction': 'Check UI event bindings and callbacks without invoking them',
  'texture.inspect': 'Read texture source, import metadata, subassets and references',
  'texture.plan_import': 'Preview texture sampling, mipmap and wrap-setting changes',
  'texture.apply_import': 'Apply guarded texture import settings, back up and verify UUID after reimport',
  'texture.restore_import': 'Restore import settings for the same asset using the current expectedHash',
  'animation.clip.read': 'Read animation source and sourceHash for guarded editing',
  'animation.clip.patch': 'Replace selected 3D vector keyframes by index, preserving other tracks and backing up',
  'animation.clip.restore': 'Restore source for the same animation UUID using its current sourceHash',
  'animation.clip.create': 'Serialize a native transform animation after validating times, tracks and target path',
  'animation.clip.inspect': 'Read native animation tracks and channel keyframe times',
  'animation.clip.sample': 'Evaluate native animation curves without applying to nodes or firing events',
  'runtime.physics2d.inspect': 'Read 2D physics enablement and gravity without changing simulation',
  'runtime.physics3d.inspect': 'Read 3D physics enablement and gravity without changing simulation',
  'runtime.physics2d.raycast': 'Query 2D fixture hits along a world-space segment, with bounded sorted results',
  'runtime.physics3d.raycast': 'Query 3D ray hits using a normalized direction and maximum distance',
  'runtime.webview.inspect': 'Inspect WebView configuration without navigation or script execution',
  'runtime.graphics.inspect': 'Read device capabilities and engine memory counters, not total driver VRAM',
  'runtime.graphics.formats': 'Query supported gfx format usages without allocating GPU resources',
  'runtime.asset.load': 'Load a local UUID asset and acquire a tool-owned reference without binding it',
  'runtime.asset.preload': 'Download a local UUID asset without parsing or rendering it',
  'runtime.asset.inspect': 'Read asset handles, reference counts and validity',
  'runtime.asset.release': 'Return only the tool-owned reference without forcing shared cache eviction',
  'runtime.bundle.inspect': 'Query loaded bundles without unloading game assets',
  'font.inspect': 'Read font type, bitmap glyph coverage and scene Label references; dynamic font coverage may be unknown',
  'scene.validate': 'Check missing components and invalid object references',
  'runtime.query': 'Read running scene and engine state', 'runtime.hierarchy': 'Read runtime node tree with pagination',
  'runtime.types': 'List accessible runtime engine types', 'runtime.inspect': 'Inspect object property descriptors and methods',
  'runtime.get': 'Read object properties', 'runtime.set': 'Set runtime object properties',
  'runtime.invoke': 'Call a public engine method', 'runtime.create': 'Construct an engine object and return a controlled handle',
  'runtime.release': 'Release an object handle, optionally destroying an owned object',
  'runtime.subscribe': 'Subscribe to object events', 'runtime.unsubscribe': 'Cancel an event subscription',
  'runtime.events': 'Read subscribed events', 'runtime.pause': 'Pause the game loop', 'runtime.resume': 'Resume the game loop',
  'runtime.capture': 'Capture the current game canvas', 'runtime.statistics': 'Read available runtime measurements',
  'shader.environment': 'Query shader toolchain, exact version and verification boundaries',
  'shader.templates': 'Read engine Effect templates and source', 'shader.read': 'Read Effect/Chunk source and content hash',
  'shader.create': 'Create and import an Effect/Chunk through AssetDB',
  'shader.update': 'Update and back up Effect/Chunk source using a hash guard',
  'shader.compile': 'Compile a native Effect and return task and dependency fingerprints',
  'shader.diagnostics': 'Query compile tasks and detect stale source',
  'shader.variants.plan': 'Generate a bounded macro combination plan',
  'shader.restore': 'Restore a resource backup only when current source matches',
  'shader.preview.connect': 'Connect an open MCP preview to the project development gateway',
  'material.query': 'Read persisted material and source hash',
  'material.create': 'Create a material using engine initialization and serialization',
  'material.clone': 'Copy a material asset to a new path',
  'material.update': 'Validate material parameters on a copy before saving and backing up',
  'material.migrate': 'Preview or apply an Effect change and parameter migration',
  'material.bindings': 'Query scene material references and asset users',
  'material.assign': 'Bind a component material slot with an old-reference guard and verify',
  'material.apply_runtime': 'Save a user-selected runtime parameter snapshot',
  'runtime.material.inspect': 'Read actual component material parameters and overrides',
  'runtime.material.update': 'Create and atomically replace an independent material instance, preserving the original on failure',
  'runtime.material.reset': 'Restore tool-modified material bindings and destroy owned instances',
  'runtime.material.compile': 'Compile material passes and report actual engine results',
  'runtime.shader.variants.compile': 'Validate bounded macro combinations using temporary instances',
  'runtime.shader.preview.open': 'Create an isolated shader preview with its own camera and test geometry',
  'runtime.shader.preview.update': 'Update preview instance parameters',
  'runtime.shader.preview.capture': 'Read preview RenderTexture pixels and generate an image',
  'runtime.shader.preview.compare': 'Compare this preview with a saved runtime baseline',
  'runtime.shader.preview.close': 'Release preview-owned nodes, materials and textures',
  'runtime.shader.profile': 'Sample whole-frame performance from real frame events; not GPU timing',
  'geometry.create': 'Create parameterized beveled Cube/Cylinder/Sphere/Torus assets and scene nodes',
  'geometry.array': 'Create bounded node-subtree arrays, preserving the source and verifying transforms',
  'rendering.query': 'Read global rendering and camera postprocessing settings with AO and transmission boundaries',
  'rendering.configure': 'Set Builtin camera Bloom/FXAA and shadow maps, then verify each setting',
  'rendering.planar_reflection': 'Create a planar reflection probe bound to a camera and MeshRenderer; verify references',
};
for (const action of ['state', 'play', 'pause', 'resume', 'stop', 'seek', 'blend']) capabilityEnglish[`runtime.animation.${action}`] = `Native animation state and playback control: ${action}`;
for (const kind of ['audio', 'video']) for (const action of ['state', 'play', 'pause', 'stop', 'seek']) capabilityEnglish[`runtime.${kind}.${action}`] = `Native ${kind} ${action}; returns current state, actual playback requires verification`;
for (const [kind, actions] of [['particle2d', ['state', 'restart', 'stop_emitting']], ['particle3d', ['state', 'play', 'pause', 'stop', 'stop_emitting']]] as const) for (const action of actions) capabilityEnglish[`runtime.${kind}.${action}`] = `Native ${kind} ${action}; rendered results require visual verification`;
for (const action of ['inspect', 'validate', 'dependencies']) capabilityEnglish[`shader.${action}`] = `Read shader ${action} results and native diagnostics`;
for (const field of ['properties', 'defines', 'states']) capabilityEnglish[`material.${field}`] = `Read material ${field} and pass data`;
