/** 面板能力说明；能力 ID 与协议中的原始目录保持稳定。 */
export const capabilityEnglish: Record<string, string> = {
  'ui.structure.plan': 'Plan Creator 2 UI nodes, hierarchy, order and component changes',
  'ui.structure.apply': 'Apply a guarded Creator 2 UI structure plan while preserving existing UUIDs',
  'editor.environment': 'Inspect Creator 2 native interface names and engine version',
  'runtime.dragonbones.inspect': 'Inspect Creator 2 DragonBones armature and animations',
  'runtime.dragonbones.play': 'Play a named Creator 2 DragonBones animation',
  'path.plan': 'Plan native spline samples and approximate constant speed',
  'path.sample': 'Sample native splines in parent-local coordinates',
  'path.bake_clip': 'Create a position animation clip from a sampled path',
  'runtime.probe.preview': 'Preview a bounded page of existing probes in world coordinates without baking',
  'runtime.path.preview': 'Transform a local path to world coordinates and draw a temporary overlay',
  'runtime.debug.draw': 'Queue bounded world-space lines on an active debug renderer',
  'runtime.debug.shape': 'Draw bounded rays, boxes, frustums and probe points',
  'runtime.skinning.plan': 'Check batch engine compatibility and shared skeletons without activation',
  'runtime.postprocess.inspect': 'Inspect the active camera pipeline and required post-process passes',
  'runtime.debug.inspect': 'Inspect owned debug drawings and rendering errors',
  'runtime.debug.clear': 'Remove only drawings belonging to the requested owner',
  'runtime.animation_graph.inspect': 'Inspect graph variables, states, transitions and weights',
  'runtime.animation_graph.trace': 'Observe graph state on actual rendered frames',
  'runtime.animation_graph.assert': 'Observe whether a debug state identifier is reached within a frame budget',
  'runtime.animation_graph.set_parameter': 'Set a typed graph parameter and read back its state',
  'probe.generate': 'Generate bounded uniform probe positions; adaptive placement is unsupported',
  'runtime.character.inspect': 'Inspect an active character controller and backend availability',
  'runtime.character.test_route': 'Execute bounded character movements and observe resulting positions',
  'runtime.skinning.inspect': 'Inspect existing skinned mesh batch configuration',
  'runtime.ik.inspect': 'Inspect animation controller availability; graph authoring is not included',
  'ik.inspect': 'Inspect a two-bone chain and native animation graph authoring availability',
  'ik.plan': 'Plan a new independent two-bone IK graph with scene fingerprint protection',
  'ik.apply': 'Create a new native IK graph asset without replacing or binding existing graphs',
  'ik.mask_create': 'Create a new animation mask after checking bone paths',
  'editor.status': 'Read editor instance, version and scene status',
  'scene.query': 'Read current scene information and dirty state',
  'scene.snapshot': 'Serialize a replayable snapshot of the current scene',
  'scene.diff': 'Compare the current scene with a baseline snapshot',
  'scene.hierarchy': 'Read scene hierarchy with pagination',
  'scene.open': 'Open a scene; reject switching with unsaved changes',
  'scene.save': 'Save the current scene and check its dirty state',
  'scene.save_copy': 'Save a new scene asset while preserving the current scene and dirty state',
  'scene.create': 'Create an empty scene through the editor',
  'scene.close': 'Close a saved scene',
  'scene.undo': 'Undo the last edit', 'scene.redo': 'Redo the last edit',
  'node.query': 'Read node and component properties',
  'node.find': 'Find all nodes matching a name or scene path',
  'node.create': 'Create a node and return its actual information',
  'node.delete': 'Delete a node', 'node.duplicate': 'Duplicate a node',
  'node.reparent': 'Change the parent, optionally preserving world transforms',
  'node.set': 'Edit node properties and verify by reading back', 'node.reset': 'Reset node transforms',
  'component.types': 'List all registered project components',
  'component.add': 'Add a built-in or project script component',
  'component.query': 'Read property descriptors for a component instance',
  'component.delete': 'Delete a component by instance ID',
  'component.set': 'Edit component properties and references, then verify',
  'component.reset': 'Reset a component instance',
  'component.invoke': 'Invoke a component method; project scripts may have arbitrary side effects',
  'asset.query': 'Query assets by type and path', 'asset.info': 'Read asset information',
  'asset.meta': 'Read import settings', 'asset.dependencies': 'Query direct asset dependencies',
  'asset.users': 'Query asset references',
  'asset.location': 'Plan a resource path by reusing an existing type folder; does not write assets',
  'asset.organize.plan': 'Preview asset organization; root only by default, skipping path-sensitive assets. Review string-based loading paths.',
  'asset.organize.apply': 'Apply a reviewed plan with matching scope and planHash; move via AssetDB, verify UUIDs and return rollback paths',
  'asset.create': 'Create a text asset through AssetDB', 'asset.save': 'Save a text asset through AssetDB',
  'asset.import': 'Import a file within the project', 'asset.copy': 'Copy an asset and its metadata',
  'asset.move': 'Move an asset while preserving its UUID', 'asset.delete': 'Delete an asset',
  'asset.refresh': 'Refresh an asset and wait for import', 'asset.reimport': 'Reimport an asset',
  'asset.set_meta': 'Merge import settings and reimport', 'asset.resolve': 'Convert between asset URL, UUID and file path',
  'prefab.instantiate': 'Instantiate a prefab in the scene', 'prefab.create': 'Save a node as a prefab asset',
  'prefab.apply': 'Apply instance changes to the prefab asset', 'prefab.revert': 'Revert prefab instance changes',
  'prefab.unlink': 'Unlink a prefab instance',
  'view.query': 'Read scene view, gizmo and grid state', 'view.set': 'Change scene view, gizmo and grid settings',
  'view.focus': 'Focus a node', 'selection.query': 'Read editor selection', 'selection.set': 'Set editor selection',
  'project.settings.get': 'Read project settings without global user credentials', 'project.settings.set': 'Edit project settings',
  'editor.messages': 'List editor messages discovered in this version',
  'editor.message': 'Invoke a discovered editor message; internal APIs require an exact version match',
  'scene.script': 'Call a scene script method of an installed extension',
  'preview.start': 'Start preview; Creator 3.8.8 uses a dedicated MCP window and requires a saved scene',
  'preview.resize': 'Resize MCP preview and capture a rendered frame; layout correctness needs review',
  'preview.input': 'Send click or wheel input to the MCP preview and capture a frame; focuses the window, business results need verification',
  'preview.stop': 'Stop project preview',
  'preview.logs': 'Query session preview errors and network failures with pagination and capture-gap reporting',
  'preview.status': 'Read MCP preview window status and recent rendering diagnostics',
  'preview.capture': 'Capture a rendered preview frame without requiring a runtime gateway',
  'logs.query': 'Query bridge events by level and page; use console.query for Creator console logs',
  'console.query': 'Read Creator console errors and stacks, filtered by level, process, keyword and cursor',
  'ui.diff': 'Compare existing UI properties while preserving UUIDs; report structural changes separately',
  'ui.apply': 'Update UI properties in place using planHash; preserve conflicts without deleting and rebuilding',
  'ui.plan': 'Plan declarative UI, checking version, references and name conflicts; return planHash',
  'ui.build': 'Build the planned UI tree and return UUID mappings; compensate partial failures locally',
  'ui.inspect_layout': 'Read actual UI corners and world bounds; detect zero size and parent overflow',
  'ui.validate_interaction': 'Check UI event bindings and callbacks without invoking them',
  'texture.inspect': 'Read texture source, import metadata, subassets and references',
  'texture.plan_import': 'Preview texture sampling, mipmap and wrap-setting changes',
  'texture.apply_import': 'Apply guarded texture import settings, back up and verify UUID after reimport',
  'texture.restore_import': 'Restore import settings for the same asset using the current expectedHash',
  'animation.clip.read': 'Read animation source and sourceHash for guarded editing',
  'animation.clip.patch': 'Replace selected 3D vector keyframes by index, preserving other tracks and backing up',
  'animation.clip.restore': 'Restore source for the same animation UUID using its current sourceHash',
  'animation.clip.create': 'Serialize a native transform animation after validating times, tracks and target path',
  'animation.clip.inspect': 'Read native animation tracks and channel keyframe times',
  'animation.clip.sample': 'Evaluate native animation curves without applying to nodes or firing events',
  'runtime.physics2d.inspect': 'Read 2D physics enablement and gravity without changing simulation',
  'runtime.physics3d.inspect': 'Read 3D physics enablement and gravity without changing simulation',
  'runtime.physics2d.raycast': 'Query 2D fixture hits along a world-space segment, with bounded sorted results',
  'runtime.physics3d.raycast': 'Query 3D ray hits using a normalized direction and maximum distance',
  'runtime.webview.inspect': 'Inspect WebView configuration without navigation or script execution',
  'runtime.graphics.inspect': 'Read device capabilities and engine memory counters, not total driver VRAM',
  'runtime.graphics.formats': 'Query supported gfx format usages without allocating GPU resources',
  'runtime.asset.load': 'Load a local UUID asset and acquire a tool-owned reference without binding it',
  'runtime.asset.preload': 'Download a local UUID asset without parsing or rendering it',
  'runtime.asset.inspect': 'Read asset handles, reference counts and validity',
  'runtime.asset.release': 'Return only the tool-owned reference without forcing shared cache eviction',
  'runtime.bundle.inspect': 'Query loaded bundles without unloading game assets',
  'font.inspect': 'Read font type, bitmap glyph coverage and scene Label references; dynamic font coverage may be unknown',
  'scene.validate': 'Check missing components and invalid object references',
  'runtime.query': 'Read running scene and engine state', 'runtime.hierarchy': 'Read runtime node tree with pagination',
  'runtime.types': 'List accessible runtime engine types', 'runtime.inspect': 'Inspect object property descriptors and methods',
  'runtime.get': 'Read object properties', 'runtime.set': 'Set runtime object properties',
  'runtime.invoke': 'Call a public engine method', 'runtime.create': 'Construct an engine object and return a controlled handle',
  'runtime.release': 'Release an object handle, optionally destroying an owned object',
  'runtime.subscribe': 'Subscribe to object events', 'runtime.unsubscribe': 'Cancel an event subscription',
  'runtime.events': 'Read subscribed events', 'runtime.pause': 'Pause the game loop', 'runtime.resume': 'Resume the game loop',
  'runtime.capture': 'Capture the current game canvas', 'runtime.statistics': 'Read available runtime measurements',
  'shader.environment': 'Query shader toolchain, exact version and verification boundaries',
  'shader.templates': 'Read engine Effect templates and source', 'shader.read': 'Read Effect/Chunk source and content hash',
  'shader.create': 'Create and import an Effect/Chunk through AssetDB',
  'shader.update': 'Update and back up Effect/Chunk source using a hash guard',
  'shader.compile': 'Compile a native Effect and return task and dependency fingerprints',
  'shader.diagnostics': 'Query compile tasks and detect stale source',
  'shader.variants.plan': 'Generate a bounded macro combination plan',
  'shader.restore': 'Restore a resource backup only when current source matches',
  'shader.preview.connect': 'Connect an open MCP preview to the project development gateway',
  'material.query': 'Read persisted material and source hash',
  'material.create': 'Create a material using engine initialization and serialization',
  'material.clone': 'Copy a material asset to a new path',
  'material.update': 'Validate material parameters on a copy before saving and backing up',
  'material.migrate': 'Preview or apply an Effect change and parameter migration',
  'material.bindings': 'Query scene material references and asset users',
  'material.assign': 'Bind a component material slot with an old-reference guard and verify',
  'material.apply_runtime': 'Save a user-selected runtime parameter snapshot',
  'runtime.material.inspect': 'Read actual component material parameters and overrides',
  'runtime.material.update': 'Create and atomically replace an independent material instance, preserving the original on failure',
  'runtime.material.reset': 'Restore tool-modified material bindings and destroy owned instances',
  'runtime.material.compile': 'Compile material passes and report actual engine results',
  'runtime.shader.variants.compile': 'Validate bounded macro combinations using temporary instances',
  'runtime.shader.preview.open': 'Create an isolated shader preview with its own camera and test geometry',
  'runtime.shader.preview.update': 'Update preview instance parameters',
  'runtime.shader.preview.capture': 'Read preview RenderTexture pixels and generate an image',
  'runtime.shader.preview.compare': 'Compare this preview with a saved runtime baseline',
  'runtime.shader.preview.close': 'Release preview-owned nodes, materials and textures',
  'runtime.shader.profile': 'Sample whole-frame performance from real frame events; not GPU timing',
  'geometry.create': 'Create parameterized beveled Cube/Cylinder/Sphere/Torus assets and scene nodes',
  'geometry.array': 'Create bounded node-subtree arrays, preserving the source and verifying transforms',
  'rendering.query': 'Read global rendering and camera postprocessing settings with AO and transmission boundaries',
  'rendering.configure': 'Set Builtin camera Bloom/FXAA and shadow maps, then verify each setting',
  'rendering.planar_reflection': 'Create a planar reflection probe bound to a camera and MeshRenderer; verify references',
};
for (const family of ['sorting', 'postprocess', 'probe']) for (const action of ['inspect', 'plan', 'apply']) capabilityEnglish[`${family}.${action}`] = `${family} ${action}: version-checked native settings with scene fingerprint protection`;
for (const action of ['state', 'play', 'pause', 'resume', 'stop', 'seek', 'blend']) capabilityEnglish[`runtime.animation.${action}`] = `Native animation state and playback control: ${action}`;
for (const kind of ['audio', 'video']) for (const action of ['state', 'play', 'pause', 'stop', 'seek']) capabilityEnglish[`runtime.${kind}.${action}`] = `Native ${kind} ${action}; returns current state, actual playback requires verification`;
for (const [kind, actions] of [['particle2d', ['state', 'restart', 'stop_emitting']], ['particle3d', ['state', 'play', 'pause', 'stop', 'stop_emitting']]] as const) for (const action of actions) capabilityEnglish[`runtime.${kind}.${action}`] = `Native ${kind} ${action}; rendered results require visual verification`;
for (const action of ['inspect', 'validate', 'dependencies']) capabilityEnglish[`shader.${action}`] = `Read shader ${action} results and native diagnostics`;
for (const field of ['properties', 'defines', 'states']) capabilityEnglish[`material.${field}`] = `Read material ${field} and pass data`;

Object.assign(capabilityEnglish, {
  'runtime.ui.inspect': 'Inspect runtime UI geometry and persisted interaction configuration',
  'runtime.ui.assert': 'Assert subtree active, text and button state without firing callbacks',
  'runtime.ui.hit_test': 'Query native screen hit candidates without firing business callbacks',
  'runtime.render2d.audit': 'Explain static 2D batching candidates; not actual submission batches',
  'runtime.label.audit': 'Inspect label cache configuration and review policy',
  'runtime.atlas.inspect': 'Read public dynamic-atlas state without changing packing',
  'runtime.physics2d.test_point': 'Query colliders containing a world point',
  'runtime.physics2d.test_aabb': 'Query colliders overlapping a world rectangle',
  'runtime.physics2d.trace_contacts': 'Sample bounded contact events and remove owned listeners',
  'runtime.spine.inspect': 'Read Spine tracks, animations and skins',
  'runtime.spine.play': 'Play or queue an existing Spine animation',
  'runtime.spine.set_skin': 'Set an existing Spine skin without replacing listeners',
  'runtime.spine.set_attachment': 'Set an existing realtime Spine slot attachment',
  'runtime.spine.trace': 'Sample native Spine tracks over actual frames',
  'runtime.tilemap.inspect': 'Read tilemap layers and object groups',
  'runtime.tilemap.query_region': 'Read bounded tile GIDs, flags and local positions',
  'runtime.tilemap.plan': 'Plan guarded runtime tile edits; source TMX is unchanged',
  'runtime.tilemap.apply': 'Apply guarded runtime tile edits with partial outcome evidence',
  'spriteframe.inspect': 'Read SpriteFrame import metadata and asset users',
  'spriteframe.plan': 'Plan nine-slice borders and atlas eligibility changes',
  'spriteframe.apply': 'Back up, import and verify guarded SpriteFrame changes',
  'spriteframe.restore': 'Restore import metadata with a current-content guard',
  'animation2d.plan': 'Plan native SpriteFrame, opacity and color tracks',
  'animation2d.create': 'Create and read back a guarded native 2D animation asset',
  'gameplay2d.templates': 'List editable gameplay component templates and required bindings',
  'gameplay2d.plan': 'Review generated component source before creating or attaching it',
  'gameplay2d.apply': 'Create and attach a guarded gameplay component; configure bindings separately',
  'ui.template.plan': 'Plan menu, inventory, HUD or dialogue UI',
  'ui.template.build': 'Build the planned UI tree and return stable node mappings',
  'level2d.plan': 'Plan seeded prefab grid placement',
  'level2d.apply': 'Apply guarded prefab placement with partial failure evidence',
  'navigation2d.find_path': 'Find a shortest four-neighbor grid route without physics claims',
  'preview.validate_viewports': 'Capture actual frames at bounded viewports and restore window size',
  'runtime.control.inspect': 'Inspect native Creator 2 control state',
  'runtime.control.scroll': 'Scroll a Creator 2 ScrollView to an offset',
  'runtime.control.page': 'Select a Creator 2 PageView page',
  'runtime.control.slider': 'Set and read back Creator 2 slider progress',
  'runtime.control.toggle': 'Set a Creator 2 toggle respecting group constraints',
  'runtime.control.text': 'Set and read back Creator 2 EditBox text',
  'scene.references': 'Audit serialized node, component and asset references in the current scene',
  'asset.references.audit': 'Audit saved serialized asset references against Creator 2 AssetDB',
  'runtime.rigidbody2d.inspect': 'Inspect Creator 2 native rigid body state and units',
  'runtime.rigidbody2d.force': 'Apply native Creator 2 force at a world point',
  'runtime.rigidbody2d.impulse': 'Apply native Creator 2 impulse at a world point',
  'runtime.joint2d.inspect': 'Inspect Creator 2 joint connections, native anchors and configuration',
  'runtime.collision2d.inspect': 'Inspect Creator 2 collision matrix and cached world geometry',
  'runtime.collision2d.trace': 'Trace bounded Creator 2 native collision callbacks without replacing business handlers',
  'runtime.resources.snapshot': 'Snapshot Creator 2 cached assets, reference counts and bundle state',
  'runtime.resources.diff': 'Compare Creator 2 resource residency against an explicit snapshot',
  'runtime.resources.trend': 'Compare retained Creator 2 snapshots across scene transitions',
  'runtime.collision2d.trace_start': 'Start a non-blocking Creator 2 collision trace',
  'runtime.task.poll': 'Read Creator 2 runtime task progress and result',
  'runtime.task.stop': 'Cancel a Creator 2 runtime task and await observer cleanup',
  'runtime.tween.plan': 'Validate bounded Creator 2 tween composition and affected node properties',
  'runtime.tween.start': 'Start an owned Creator 2 tween with cancellable frame sampling',
  'runtime.dragonbones.trace_start': 'Trace native Creator 2 DragonBones animation events without replacing business listeners',
  'runtime.dragonbones.fade': 'Blend Creator 2 DragonBones animations by native layer, group and fade-out rules',
  'runtime.physics2d.contact_trace_start': 'Trace Creator 2 Box2D contact phases, world manifolds and normalized impulses',
  'runtime.dragonbones.details': 'Inspect Creator 2 DragonBones bones, slots and animation states with cached-mode limits',
  'runtime.spine.trace_start': 'Trace Creator 2 Spine animation events with explicit cache-mode boundaries',
  'runtime.spine.mix.inspect': 'Inspect Creator 2 Spine animation pair mixing duration',
  'runtime.spine.mix.update': 'Update Creator 2 Spine mixing with expected-state guard and native readback',
  'runtime.spine.details': 'Inspect Creator 2 Spine bones, slots and tracks with explicit cached-mode limits',
  'runtime.camera.inspect': 'Inspect Creator 2 camera projection and render target state',
  'runtime.camera.convert': 'Convert Creator 2 camera coordinates with normalized 3D projection depth',
  'runtime.camera.culling': 'Inspect Creator 2 camera group-mask matching without claiming visibility',
  'runtime.camera.sample_pixels': 'Sample RGBA pixels with a temporary Creator 2 render texture and restore camera state',
});
